"use client";
import {useEffect,useMemo,useState} from "react";
import {useRouter} from "next/navigation";
type U={id:string;email:string;name:string;created_at:string;card_slug:string|null};
export default function AdminDashboard(){
 const r=useRouter(),[users,setUsers]=useState<U[]>([]),[days,setDays]=useState("30"),[err,setErr]=useState("");
 useEffect(()=>{fetch("/api/admin/users",{cache:"no-store"}).then(async x=>{const j=await x.json();if(!x.ok)throw Error(j.error);setUsers(j.users||[])}).catch(e=>setErr(e.message))},[]);
 const f=useMemo(()=>days==="all"?users:users.filter(u=>Date.now()-+new Date(u.created_at)<=+days*86400000),[users,days]);
 const today=users.filter(u=>new Date(u.created_at).toDateString()===new Date().toDateString()).length;
 async function logout(){await fetch("/api/admin/logout",{method:"POST"});r.replace("/admin/login");r.refresh()}
 return <main className="a"><header><b>VisiteCard <i>Admin</i></b><button onClick={logout}>Déconnexion</button></header><div className="w"><div className="top"><div><small>ADMINISTRATION</small><h1>Tableau de bord</h1><p>Suivi des inscriptions VisiteCard.</p></div><select value={days} onChange={e=>setDays(e.target.value)}><option value="7">7 jours</option><option value="30">30 jours</option><option value="90">90 jours</option><option value="all">Toute la période</option></select></div>{err&&<div className="err">{err}</div>}<section className="stats"><article>Total inscrits<strong>{users.length}</strong></article><article>Aujourd'hui<strong>{today}</strong></article><article>Sur la période<strong>{f.length}</strong></article></section><section className="box"><h2>Tous les inscrits</h2><div className="table"><table><thead><tr><th>Nom</th><th>E-mail</th><th>Inscription</th><th>Carte</th></tr></thead><tbody>{f.map(u=><tr key={u.id}><td>{u.name||"—"}</td><td>{u.email}</td><td>{new Date(u.created_at).toLocaleString("fr-FR")}</td><td>{u.card_slug?<a href={"/"+u.card_slug} target="_blank">Voir</a>:"—"}</td></tr>)}</tbody></table></div></section></div><style jsx>{`*{box-sizing:border-box}.a{min-height:100vh;background:#f7f7f8;font-family:Arial;color:#171717}header{height:72px;background:#fff;border-bottom:1px solid #e8e8e8;display:flex;align-items:center;justify-content:space-between;padding:0 max(20px,calc((100vw - 1180px)/2))}header i,small,a{color:#ff6337;font-style:normal}button{padding:10px 14px;border:1px solid #ddd;border-radius:10px;background:#fff;font-weight:800}.w{width:min(1180px,calc(100% - 30px));margin:35px auto}.top{display:flex;justify-content:space-between;align-items:end}.top h1{font-size:35px;margin:7px 0}.top p{color:#777}.top select{padding:12px;border:1px solid #ddd;border-radius:11px}.stats{display:grid;grid-template-columns:repeat(3,1fr);gap:16px;margin:25px 0}.stats article,.box{background:#fff;border:1px solid #e8e8ea;border-radius:18px;padding:22px}.stats article{color:#777;font-size:13px}.stats strong{display:block;color:#111;font-size:35px;margin-top:12px}.table{overflow:auto}table{width:100%;min-width:700px;border-collapse:collapse}th,td{text-align:left;padding:14px 10px;border-bottom:1px solid #eee;font-size:13px}th{color:#777}.err{background:#fee;color:#a11;padding:12px;margin-top:15px;border-radius:10px}@media(max-width:700px){.stats{grid-template-columns:1fr}.top{display:grid;gap:12px}}`}</style></main>
}
