"use client";

import { FormEvent, useEffect, useState } from "react";
import { getSupabaseBrowser } from "../../lib/supabase";
import { useLanguage } from "@/components/LanguageProvider";

export default function ProfilPage(){
  const {lang}=useLanguage();const fr=lang==="fr";
  const[email,setEmail]=useState("");const[newPassword,setNewPassword]=useState("");const[confirm,setConfirm]=useState("");const[msg,setMsg]=useState("");const[error,setError]=useState("");
  useEffect(()=>{(async()=>{const s=getSupabaseBrowser();const{data}=await s.auth.getUser();setEmail(data.user?.email||"")})()},[]);
  async function changeEmail(e:FormEvent){e.preventDefault();setMsg("");setError("");try{const s=getSupabaseBrowser();const{error}=await s.auth.updateUser({email});if(error)throw error;setMsg(fr?"Demande de modification envoyée. Vérifiez votre e-mail si une confirmation est demandée.":"Update request sent. Check your email if confirmation is required.")}catch(x:any){setError(x.message||"Erreur")}}
  async function changePassword(e:FormEvent){e.preventDefault();setMsg("");setError("");if(newPassword.length<6){setError(fr?"Le mot de passe doit contenir au moins 6 caractères.":"Password must contain at least 6 characters.");return}if(newPassword!==confirm){setError(fr?"Les mots de passe ne correspondent pas.":"Passwords do not match.");return}try{const s=getSupabaseBrowser();const{error}=await s.auth.updateUser({password:newPassword});if(error)throw error;setNewPassword("");setConfirm("");setMsg(fr?"Mot de passe modifié.":"Password updated.")}catch(x:any){setError(x.message||"Erreur")}}
  async function logout(){const s=getSupabaseBrowser();await s.auth.signOut();localStorage.removeItem("visitecard_access_token");localStorage.removeItem("visitecard_refresh_token");localStorage.removeItem("visitecard_user");window.location.href="/connexion"}
  return <main className="dashBody"><div className="pageTitle"><span>VISITECARD</span><h1>{fr?"Mon profil":"My profile"}</h1><p>{fr?"Gérez vos informations de connexion.":"Manage your sign-in information."}</p></div>{error?<div className="notice">{error}</div>:null}{msg?<div className="vcSuccess">{msg}</div>:null}<div className="profileGrid"><form className="panel" onSubmit={changeEmail}><h2>{fr?"Adresse e-mail":"Email address"}</h2><label>{fr?"E-mail":"Email"}<input type="email" required value={email} onChange={e=>setEmail(e.target.value)}/></label><button className="smallBtn">{fr?"Modifier mon e-mail":"Update email"}</button></form><form className="panel" onSubmit={changePassword}><h2>{fr?"Mot de passe":"Password"}</h2><label>{fr?"Nouveau mot de passe":"New password"}<input type="password" required value={newPassword} onChange={e=>setNewPassword(e.target.value)}/></label><label>{fr?"Confirmer":"Confirm"}<input type="password" required value={confirm} onChange={e=>setConfirm(e.target.value)}/></label><button className="smallBtn">{fr?"Modifier le mot de passe":"Update password"}</button></form></div><div className="panel vcLogoutPanel"><div><h2>{fr?"Session":"Session"}</h2><p>{fr?"Déconnectez-vous de votre espace VisiteCard.":"Sign out of your VisiteCard space."}</p></div><button onClick={logout}>{fr?"Déconnexion":"Sign out"}</button></div><style jsx>{`.vcSuccess{padding:14px 16px;border-radius:14px;margin-top:18px;background:#ecfdf3;color:#087a42}.vcLogoutPanel{margin-top:20px;display:flex;align-items:center;justify-content:space-between;gap:20px}.vcLogoutPanel h2{margin:0}.vcLogoutPanel p{margin:8px 0 0;color:#7c8799}.vcLogoutPanel button{border:0;background:#111827;color:#fff;padding:13px 17px;border-radius:12px;font-weight:800;cursor:pointer}@media(max-width:600px){.vcLogoutPanel{align-items:stretch;flex-direction:column}.vcLogoutPanel button{width:100%}}`}</style></main>
}
